# This sketch will add 2 switches named <upper_devicename> Setup Switch and Setup Button
# Use your mobile or tablet and connect to http://<devicename>.local to set up the blind
#   Turn on the Setup Switch to enter Setup Mode and use the Setup Button as shown below to setup blinds.
# 1) Turn on the Setup Switch to enter setup mode
# 2) Press Setup button to start the blind closing
# 3) Press Setup button again when closed and blind starts to open (actually resets the stepper position to 0)
# 4) Press Setup button again when blind is fully open
# 5) Job Done

# This sketch also includes a momentary button on D7 which can be used in the following way
# 1) Press button for > 1 second to enter setup mode
# 2) Press button again to start the blind closing
# 3) Press button again when closed and blind starts to open (actually resets the stepper position to 0)
# 4) Press button again when blind is fully open
# 5) Job Done

# Button is also used to open/close the blind (must be fully open/closed first)

# NOTE:  If you find that your shades are going the wrong way, you can change the pin
#        settings below or reverse the + and – wires for each of the A and B motor
#        pairs on your driver and the motor will spin in the opposite direction.

# The following pins are for the original 'Motor on a Roller Blind'

substitutions:
  devicename: roller_blind
  upper_devicename: Roller Blind
  mystepper: my_stepper
  pina: D1
  pinb: D3
  pinc: D2
  pind: D4
# Wrong direction? Comment the previous 4 lines and uncomment the following 4 
#  pina: D3
#  pinb: D1
#  pinc: D4
#  pind: D2

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: True
  on_boot:
    - priority: -200.0
      then:
      - stepper.report_position: # Set stepper to global variable
          id: $mystepper
          position: !lambda return id(${mystepper}_global);
      - stepper.set_target: # Set stepper to global variable
          id: $mystepper
          target: !lambda return id(${mystepper}_global);

wifi:
  networks: 
    - ssid: !secret wifi
      password: !secret wifi_password

  ap:
    ssid: $upper_devicename
    password: !secret wifi_password

web_server:
  port: 80

logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

captive_portal:

stepper:
  - platform: uln2003
    id: $mystepper
    pin_a: $pina
    pin_b: $pinb
    pin_c: $pinc
    pin_d: $pind
    max_speed: 600 steps/s # Speed of the motor
    sleep_when_done: True
    acceleration: inf
    deceleration: inf

globals:
  - id: ${mystepper}_global # Integer for storing the stepper position in case of reboot
    type: int
    restore_value: True
    initial_value: '0'

  - id: openclosed # Boolean to store OPEN/CLOSED state
    type: bool
    restore_value: True
    initial_value: '0'

  - id: endstop # Variable for storing ENDSTOP (how far to move stepper)
    type: int
    restore_value: True
    initial_value: '1000'

  - id: settingmode # Integer for Setup Mode
    type: int
    restore_value: no
    initial_value: '0'

  - id: settingup # Boolean for Setup Active
    type: bool
    restore_value: no
    initial_value: '0'

binary_sensor:
  - platform: gpio
    pin:
      number: D7 # Connect Button to D7 and GND
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    internal: True
    on_click:
    - min_length: 50ms
      max_length: 500ms
      then: # Short press to OPEN/CLOSE blinds and also for setting up
        - script.execute: moveit
    - min_length: 1000ms
      max_length: 3000ms
      then: # Long press to Enter Setting Mode
        - script.execute: setting

switch:
  - platform: template
    name: ${upper_devicename} Setup Switch # Switch to enter Setup Mode
    id: setupswitch
    lambda: |-
      if (id(settingup)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - script.execute: setting
    turn_off_action:
      - logger.log: "Exiting Settings Mode"
      - globals.set:
          id: settingup
          value:  '0'
      - globals.set:
          id: settingmode
          value:  '0'
  - platform: template
    name: ${upper_devicename} Setup Button # Switch to replicate the Physical Button
    id: hasetup
    turn_on_action:
      - if: # If settings variable is on
          condition:
            - lambda: 'return id(settingup);'
          then: # Enter Setting Mode
            - script.execute: setupbutton
            - switch.turn_off: hasetup

cover:
  - platform: template
    name: $upper_devicename
    id: blinded
    lambda: |-
      if (id(openclosed)) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - script.execute: openscript
    close_action:
      - script.execute: closescript
    position_action:
#      - script.execute: positional
      then:
        - stepper.set_target:
            id: $mystepper
            target: !lambda return id(endstop) * pos;
        - wait_until: # Wait until 0 reached
            lambda: 'return id($mystepper).current_position == (id(endstop) * pos);'
        - globals.set: # Set global to current position
            id: ${mystepper}_global
            value: !lambda return id($mystepper).current_position;
    stop_action:
      then:
        - stepper.set_target:
            id: $mystepper
            target: !lambda return id($mystepper).current_position;
        - globals.set: # Set global to current position
            id: ${mystepper}_global
            value: !lambda return id($mystepper).current_position;
        - script.stop: openscript
        - script.stop: closescript
    has_position: true
    device_class: blind

script:
  - id: moveit
    then:
      - if: # If settings variable is on
          condition:
            - lambda: 'return id(settingup);'
          then: # Enter Setting Mode
            - script.execute: setupbutton
          else:
            - if: # If blind is closed
                condition:
                  - lambda: 'return id(openclosed) == 0;'
                then: # Open blind
                  - script.execute: openscript
                else: # Close blind
                  - script.execute: closescript

  - id: openscript
    then:
      - logger.log: "Opening"
      - stepper.set_target: # Send stepper to endstop
          id: $mystepper
          target: !lambda return id(endstop);
      - wait_until: # Wait until endstop reached
          lambda: 'return (id($mystepper).current_position == id(endstop));'
      - globals.set: # Set global to current position
          id: ${mystepper}_global
          value: !lambda return id($mystepper).current_position; 
      - globals.set: # Set toggle to OPEN (No need for 'optimistic mode')
          id: openclosed
          value: '1'
      - logger.log:
          format: "The position is being reported as %d, endstop is %d"
          args: [ 'id($mystepper).current_position','id(endstop)' ]

  - id: closescript
    then:
      - logger.log: "Closing"
      - stepper.set_target: # Send stepper to 0
          id: $mystepper
          target: '0'
      - wait_until: # Wait until 0 reached
          lambda: 'return (id($mystepper).current_position == 0);'
      - globals.set: # Set global to current position
          id: ${mystepper}_global
          value: !lambda return id($mystepper).current_position; 
      - globals.set: # Set toggle to CLOSED (No need for 'optimistic mode')
          id: openclosed
          value: '0'

  - id: setting
    then:
      - logger.log: "Entered Settings Mode"
      - globals.set:
          id: settingup
          value:  '1'
      - globals.set:
          id: settingmode
          value:  '1'

  - id: setupbutton
    then:
      - if:
          condition:
            - lambda: 'return (id(settingmode) == 3);'
          then:
            - logger.log: "Pressed Setup Button: Mode 3"
            - stepper.set_target: # Set Stepper position
                id: $mystepper
                target: !lambda return id($mystepper).current_position;
            - globals.set: # Set Endstop Variable
                id: endstop
                value: !lambda return id($mystepper).current_position;
            - globals.set: # Set Global stepper position
                id: ${mystepper}_global
                value: !lambda return id($mystepper).current_position;
            - globals.set: # Reset Setting Mode
                id: settingmode
                value:  '0'
            - globals.set: # Reset Setting Mode
                id: settingup
                value:  '0'
            - globals.set: # Set toggle to Open
                id: openclosed
                value: '1'
            - logger.log: "Exiting Setting Mode"
      - if:
          condition:
            - lambda: 'return (id(settingmode) == 2);'
          then:
            - logger.log: "Pressed Setup Button: Mode 2"
            - stepper.report_position: # Reset Stepper position to 0
                id: $mystepper
                position: '0'
            - stepper.set_target: # Reset Stepper position to 0
                id: $mystepper
                target: '0'
            - globals.set: # Move stepper to 0 (doesn't move it's already there!)
                id: ${mystepper}_global
                value: '0'
            - stepper.set_target: # Reset Stepper position to 72000
                id: $mystepper
                target: '72000'
            - globals.set: # Advance setup to next mode
                id: settingmode
                value:  '3'
      - if:
          condition:
            - lambda: 'return (id(settingmode) == 1);'
          then:
            - logger.log: "Pressed Setup Button: Mode 1"
            - stepper.report_position: # Set Stepper position to 72000, makes it move to 0 (Closed)
                id: $mystepper
                position: '72000'
            - globals.set: # Advance setup to next mode
                id: settingmode
                value:  '2'
