#https://github.com/RoadkillUK/Motor-on-a-Roller-Blind-for-ESPHOME - Written by RoadkillUK

substitutions:
  devicename: roller_blind
  upper_devicename: Roller Blind
  mystepper: my_stepper # Name of the stepper motor (leave as is)
  speed: 600 steps/s # Set the speed of the motor
  pina: D1 # Swap these \_ coil a
  pinb: D3 # Swap these /
  pinc: D2 # Swap these \_ coil b
  pind: D4 # Swap these /
<<: !include .common_blind.yaml # comment this line and uncomment the following line to enable the no_delay version.
# <<: !include .common_blind_no_delay.yaml

# NOTE:  If you find that your shades are going the wrong way, you can change the pin
#        settings or reverse the + and – wires for each of the A and B motor
#        pairs on your driver and the motor will spin in the opposite direction.

# These pinouts are for the original 'Motor on a Roller Blind'